### ISSUE TITLE
Please distribute an unmodified GPL-3 license text

### ISSUE THREAD

**Issue by peti** [mdibaiee/sibe#2]
Hi, I would like to add this library to the openSUSE Linux distribution, but our lawyers have complained that your package is technically not licensed under GPL-3 because the LICENSE file you distribute is not a verbatim copy of <https://www.gnu.org/licenses/gpl-3.0.txt>. Would you mind releasing a point update of this package that remedies this issue?

**Comment by mdibaiee** [comment]
Hi @peti, thanks for the pull-request. I see your point, my mistake. :+1:

**Comment by peti** [comment]
Can you please release the fixed version to Hackage?

**Comment by mdibaiee** [comment]
@peti: https://hackage.haskell.org/package/sibe-0.2.0.5

**Comment by peti** [comment]
Thank you!
